### ISSUE TITLE
Some issues with your code

### ISSUE THREAD

**Issue by mcoolin** [manzerbredes/pgnp#3]
Good day,

I am looking at your code for a project of mine. Looks promising but I noticed two issues:
1. You reference #include "CMI.hpp" but don't include the file. Is this another project?
2. Your read.me states to include the #include "pgnp.hpp", but no such file exists, do you mean pgn.hpp?

Thanks Mike

**Comment by manzerbredes** [comment]
Hi,
if you followed the steps from the **README.md** all these files must be generated out of the compilation phase.
Also, be sure to use `git clone --recursive https://gitlab.com/manzerbredes/pgnp` to fetch submodules.

**Comment by mcoolin** [comment]
Thanks for that, it does compile, and I have the missing files.
